### ISSUE TITLE
Example apps crash on flutter 3.22.1

### ISSUE THREAD

**Issue by moovida** [mikes222/mapsforge_flutter#102]
Hi, I am experiencing crashes of the example applications on flutter 3.22.1. I suppose it is due to the svg package. All the error I get is the following:

```
flutter: 2024-05-23 09:28:27.669936	_MapviewWidgetState	[INFO]:	MapModel created with renderer key 1064286925 in connectionState ConnectionState.done
flutter: 2024-05-23 09:28:27.723144	_MapviewWidgetState	[INFO]:	ViewModel created in connectionState ConnectionState.done
flutter: 2024-05-23 09:28:27.931900	MapDataStoreRenderer	[INFO]:	138 ms: 323 ways and 30 pois read for tile Tile{tileX: 35121, tileY: 21986, zoomLevel: 16, indoorLevel: 0}
flutter: unhandled element <metadata/>; Picture key: Svg loader
```

Anyone experiencing the same?

**Comment by mikes222** [comment]
This does not seem like a crash to me. It is just a warning that the svg loader does not recognize the element metadata or the element is malformed. In my experience everything works as expected besides this warning. If you feel otherwise it would be nice to have a simple testcase so that I can examine it.

**Comment by moovida** [comment]
Oh, that is interesting. I am running your example apps from a clean repo checkout of yours. 
But I am running the linux version and that once crashes. I assume it will not on android.ios. 
I will check as soon as I am able to and report back.
