### ISSUE TITLE
External renderthemes

### ISSUE THREAD

**Issue by moovida** [mikes222/mapsforge_flutter#11]
Hi, I wanted to see if there is a way, even manual, to load external renderthemes. I would appreciate if you could give me some hint and correction on my guesses. 

Let's take the example of openandromaps, I downloaded an elevate.zip theme, which is supposed to also show contourlines and different styling.
It is made of:

* a rendertheme xml
* a folder containing all the necessary svg

Creating a rendertheme using that xml is simple, but I assume the issue is to load all the internally referenced svg using the paths relative to the .map file?

Do you think it would be fairly easy to do this enhancement? (Speak: I would be able to do it and you would appreciate it as contribution?)

Having a way to see offline contour lines in the mountains would be quite useful :-)

**Comment by mikes222** [comment]
jup, rendertheme download is easy since it is up to the dev to implement the download and handle the binary to the renderthemebuilder. btw. it may make sense to provide a helper method to do this if you like to support downloading from http https

Downloading svg's should also be quite easy. By default images in the rendertheme are referenced by e.g. `jar:patterns/military.png`. This is converted by `SymbolCache` in the necessary steps to load the file from the assets and read it as svg. Enhance that class to load files from http(s) if the prefix is `http:` or `https:`
It may make sense to split the loading/downloading part from the conversion of the binary svg/png content into two or more separate classes
Create Testcases for it multiple cases and submit a pull request

**Comment by moovida** [comment]
It is not that much the downloading of themes, since I do not think there is a standard way. But the user could just download it, even manually, and place it on the device. 

> This is converted by SymbolCache in the necessary steps to load the file from the assets and read it as svg.

This is what I think does not work. I.e. I do not want to be forced to put all the svg/png referenced in the assets. That is ok for the default render Theme. But a user should be able to download a map with a custom theme, unzip it and have the svg folder at the same level of the map file and the custom render theme xml. In that case the ```jar:patterns/military.png``` should resolve to a relative path of the rendertheme/mapfile. But currently it only does internal assets or am I wrong?

We have this like that in geopaparazzi and users where quite happy. But yes, we always check if there is an xml near the map file that has the same name. In that case the custom render theme is pulled instead of the internal.

**Comment by mikes222** [comment]
Similar thing: 
Separate the loading/downloading part in `SymbolCache` to another class - For example create plugins for the loading/downloading part in `SymbolCache`. 
Provide the default plugin which does what it does now - get the images from the assets and return the binary content to the `SymbolCache`. 
Provide a new plugin which does what it should do for your scenario - get the images from a specified directory and return the binary content to the `SymbolCache`. 

The dev needs to decide which plugin is registered/loaded into the `SymbolCache` so that `SymbolCache` is able to load the images based on the given plugin. 

btw. downloading and unzipping is imho implemented in the example project of mapsforge - it comes as a side-feature. You could copy it into your project when needed.

**Comment by moovida** [comment]
Thanks for the input, I will go through it with code at hand as soon as possible.

**Comment by moovida** [comment]
I have finally been able to give this a run and show contourlines from http://www.openandromaps.org. The result seems to be the expected, but I am not sure yet if this doesn't have ramifications:

![image](https://user-images.githubusercontent.com/390250/90530918-b908b400-e175-11ea-892b-856e1d34a129.png)

It will probably need a bit of discussion to make a PR from this, since in several places you had the relativePath removed, which is necessary to get the svgs from nearby folders. I added them back where I found **null** placeholder, but am not sure if other elements also had it before (ex. Area, RenderCircle...).

If you are interested in this addition, I would be happy to chat and try to get a PR together afterwards.

**Comment by mikes222** [comment]
Since I was not able to reach out to you I ask you to create a PR for this feature.

**Comment by moovida** [comment]
Hi @mikes222 , I hope it was because of lack of time to get to me and not because you wrote me and I didn't see your email.

Anyways I can try to cleanup and do a PR.

**Comment by mikes222** [comment]
I would like to see a pull request regarding the hillshading features you mentioned above.

**Comment by moovida** [comment]
Yes, I apologize and I am up to make this as soon as possible on the current codebase

**Comment by moovida** [comment]
Hi, I have a question, is the current master the way to go?

I made a pull and now I have a set of errors in the codebase.
Things like:
```
import 'file:///E:/develop/github_mapsforge_flutter/mapsforge_flutter/lib/src/exceptions/mapfileexception.dart';
```

or 
```
import 'package:dio/dio.dart';
```
when dio is not one of the defined packages.

Any idea what might be happening?

**Comment by moovida** [comment]
Oh, sorry, it seemed to be the IDE going crazy. But the first import issue is there.

**Comment by moovida** [comment]
Opened PR #17

**Comment by mikes222** [comment]
Thanks for fixing my bugs! I have already accepted your PullRequest. Can you add an example to the example app?

**Comment by moovida** [comment]
I wanted to add an example but then I refrained. I am not sure how to do that without tons of code. The thing is that it would require to download a complete theme folder (or zip) with all the svgs and copy them to the card nearby a map file that contains that info.

**Comment by mikes222** [comment]
I can provide the zip at my server and implement the code to download and unzip. Just send me a link to the zip file (e.g. google drive or firefox download or whatever you want).

**Comment by moovida** [comment]
Great thank you!
Let me look for the smallest map file of andromaps that I can find, so that the download is as short as possible.

**Comment by moovida** [comment]
Ok, here we go. In the end the smallest I found that also would have some nice mountain to show contours on, is the Sicily map, with its Etna vulcano.
It is 150MB zipped, hope that is ok: https://we.tl/t-8r2BAXxc9q
The archive contains all that's needed already with the right naming. So unzipping it somewhere in a dedicated folder would be great.
Thank you!

**Comment by mikes222** [comment]
Now implemented your example in the APP.
