### ISSUE TITLE
Question about markers

### ISSUE THREAD

**Issue by berthely1981** [mikes222/mapsforge_flutter#54]
Hello, I tried to add differents maker on MarkerdemoDatastore class, it works with the CircleMarker, circles show, but 
Marker, BasicMarker, BasicPointMarker the maker not show only the Caption is showed, with PoiMarker 
get this on console:
"BitmapMixin	[WARNING]:	Unable to load asset: assets/icons/marker_red.png, ignore missing bitmap in rendering" and only the  Caption is showed, Not sure how add src correctly.

this is my code;

`
Future<Marker> _createBasicMarker(TapEvent tapEvent) async {
    debugPrint('>>>_createBasicMarker');
    BasicMarker marker = BasicMarker(
        item: tapEvent,
        markerCaption: MarkerCaption(
            text: 'BasicMarker', latLong: tapEvent)
    );
    marker.markerCaption?.initResources();
    return marker;
  }

  Future<Marker> createBasicPointMarker(TapEvent tapEvent) async {
    debugPrint('>>>createBasicPointMarker');
    BasicPointMarker marker = BasicPointMarker(
      item: tapEvent, latLong: LatLong(tapEvent.latitude,tapEvent.longitude),
        markerCaption: MarkerCaption(
            text: 'BasicPointMarker', latLong: tapEvent)
    );
    // await marker.initResources(symbolCache);
    return marker;
  }

  Future<Marker> createPoiMarker(TapEvent tapEvent) async {
    debugPrint('>>>createPoiMarker');
    PoiMarker marker = PoiMarker(
        item: tapEvent, latLong: LatLong(tapEvent.latitude,tapEvent.longitude),markerCaption:MarkerCaption(
        text: 'markerCaption createPoiMarker')
        , src:'assets/icons/marker_red.png'
    );
    await marker.initResources(symbolCache);
    return marker;
  }
`
What Im missing to show the markers? How add src correctly to PoiMarker?

Thanks for this awesome project.

**Comment by mikes222** [comment]
In order to load the png ```assets/icons/marker_red.png``` make sure the png exists at the specified position and also add the information about the png to the ```pubspec.yaml``` file. 
If that does not help please try to specify the colors for fill and stroke. 
In case you find a problem or you want to enhance the docu just solve it and create a PullRequest so that everyone can take advantage of your findings.

**Comment by berthely1981** [comment]
Thanks for response, for the poi src I add full path in pubspec.yaml 

  assets:
   - assets/render_themes/
   - assets/icons/
   - assets/icons/marker_green.png
   - assets/icons/marker_red.png
   ... 
 
set only - assets/icons/ dont work.

**Comment by vedranivicatos** [comment]
> btw. Marker, BasicMarker, BasicPointMarker are all base classes to derive from

Is there an example of overriding these classes to use one's own marker? I am trying to put custom "myLocation" marker. I have tried using the PoiMarker with svg source but it renders quite poorly (blurry).



> Maybe we should specify these classes as abstract to avoid confusion

Yes definitely. There's a couple of places in code where I feel like things should have been made private, not exposed to other classes, abstract etc. But regardless, very useful plugin, hope it keeps getting maintained further. Thanks and best of luck.

**Comment by mikes222** [comment]
Please create Pull Requests with your desired changes. My view of this project is most likely quite different from your view. I do not see what may confuse you. 
Examples are RectMarker, CircleMarker or PoiMarker as well as PolygonMarker. 
Regarding your blurry image: Try a different svg or create a new Issue with screenshots and the original svg (and a testcase would be nice) so that I can try to reproduce or give you a hint.

**Comment by vedranivicatos** [comment]
Okay, thanks, I will create a new issue regarding the blurry marker image on iOS with some code to reproduce, svg file used and screenshots. 

> Examples are RectMarker, CircleMarker or PoiMarker as well as PolygonMarker.

Also, I am able to use the RectMarker, PolygonMarker and others but the CircleMarker class is not in the code. I am using Flutter 3.0.0 and mapsforge_flutter 2.0.1. Could this be a simple version issue?

**Comment by mikes222** [comment]
The code works for iOS? Great. I have never used iOS by myself nor tested it.

Please use the code from github instead of pub.dev like so:

    mapsforge_flutter: #2.0.1
      git: https://github.com/mikes222/mapsforge_flutter

This code is much more advanced. When you need to publish drop me a note and I will publish the latest code to pub.dev for you. Make sure everything works for you (request PullRequests before) before I publish code.

btw. If you create a testcase (unittest) we can test your issue everytime with the newest source. It is better to do so and easier for me instead of describing everything in an issue.

**Comment by vedranivicatos** [comment]
> Also, I am able to use the RectMarker, PolygonMarker and others but the CircleMarker class is not in the code. I am using Flutter 3.0.0 and mapsforge_flutter 2.0.1. Could this be a simple version issue?

When adding the plugin (the current git version) using: 
```
  mapsforge_flutter:
    git:
      url: https://github.com/mikes222/mapsforge_flutter
      path: mapsforge_flutter

```
The code is much different and yes the CircleMarker is indeed there. However, if I use:
`  mapsforge_flutter: ^2.0.1`  
it is not there as the code is not the same anymore. As the `  mapsforge_flutter: ^2.0.2`  does not resolve to any available versions, I believe the git version (2.0.2) needs to be published to pub.dev perhaps?

**Comment by mikes222** [comment]
The code from github is the most recent code. Sometimes in the future I will publish this code to pub.dev as 2.1.0 or so. Before doing so I encourage you to use the code from github and make sure everything is working for you. 

The mapsforge community is quite small so I can currently afford to only publish on request.

**Comment by vedranivicatos** [comment]
Okay I understand, I will be using the git version of the plugin. I have tried CircleMarker just now and it does exactly what I need, it's pretty good. Thanks
