### ISSUE TITLE
Windows: Using local file + rendering quality

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#58]
I've downloaded this repo and compiled the example targeting the Windows desktop.

Q1: Using local file
I haven't found a way to add a local file. As a workaround I used http://localhost to point to the file. Is there a way to point the app to a local file instead of using a Url?

Q2: Quality of Map display
I'm using a local Mapsforge file downloaded from https://download.mapsforge.org/maps/v5/europe/. The same file used in an Android/Kotlin app using the Mapsforge library looks very crisp.
Unfortunately, using the same file inside the mapsforge_flutter example gives a rather poor result.
- The elements in the map are displayed differently
- The map is lacking details which are available in the Android/Mapsforge app.

Any suggestions?

**Comment by mikes222** [comment]
You have 2/3 problems and you should therefore open multiple requests to avoid mixing up everything.

ad 1: Sure. The example APP is just an example. It downloads the mapfiles from various sources and displays them. When you integrate mapsforge in your own app you can decide by yourself how to provide the mapfiles. 

ad 2: Please provide sample images here that we can see what is missing and what you mean. Also provide the location of the sample images so that we can reproduce it. See also #55, it may answer your crisp/blurr question already.

**Comment by pamtbaau** [comment]
I'll start afresh...
